name: Run pytest
on:
  pull_request:

permissions:
  contents: write
  checks: write
  issues: write
  pull-requests: write

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # 環境変数を読み込む
      - name: Load environment variables
        run: |
          python -c "import yaml; env = yaml.safe_load(open('.github/workflows/env.yaml')); [print(f'{key}={value}') for key, value in env['env'].items()]" >> $GITHUB_ENV
          echo ${{ env.PYTHON_VERSION }}

      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: env.PYTHON_VERSION

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          python -m pytest test --junit-xml results/pytest.xml
        continue-on-error: true

      # テスト結果の表示
      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results (Python 3.7)
          path: results/*.xml

      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: artifacts/**/*.xml
